server:
  port: 8081

spring:
  application:
    name: order-service
  datasource:
    url: jdbc:postgresql://localhost:5432/OrderDb
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  config:
    import: configserver:http://localhost:8082
    cloud:
      config:
        fail-fast: true

  management:
    tracing:
      enabled: true
      sampling:
        probability: 1.0
  zipkin:
    tracing:
      endpoint: https://localhost:9411/
